# -*- coding: utf-8 -*-
"""Weathers Api.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10TdD6QVvfx1eJquWI0aTF55oHtS8A2ym
"""

# OpenMap Api Fetch ------------------------------------------------------------

import requests

api_key = '33cb808325c68f009bd043f19e5f591f'

city_name = "karachi"
url = f"https://api.openweathermap.org/data/2.5/weather?q={city_name}&appid={api_key}"
#print(url)

req = requests.get(url)
data = req.json()
#print(data)

name = data['name']
temp = round(((data['main']['temp']) - 273.15),2)
description = data['weather'][0]['description']
feels_like = round(((data['main']['feels_like']) - 273.15),2)
temp_min = round(((data['main']['temp_min']) - 273.15),2)
temp_max = round(((data['main']['temp_max']) - 273.15),2)
pressure = data['main']['pressure']
humidity = data['main']['humidity']
wind_speed = round(((data['wind']['speed']) * 2.23694) * 2)
wind_dir = data['wind']['deg']
clouds = data['clouds']['all']
sea_level = data['main']['sea_level']
ground_level = data['main']['grnd_level']

print("Name:\t\t",name)
print("Temerature:\t",temp, "°C")
print("Description:\t",description)
print("Feels Like:\t",feels_like, "°C")
print("Temp Min:\t",temp_min, "°C")
print("Temp Max:\t",temp_max, "°C")
print("Pressure:\t",pressure, "hPa")
print("Humidity:\t",humidity, "%")
print("Wind Speed:\t",wind_speed, "mph")
print("Wind Dir:\t",wind_dir, "°")
print("Clouds:\t\t",clouds, "%")
print("Sea Level:\t",sea_level, "hPa")
print("Ground Level:\t",ground_level, "hPa")

import json

OpenWeatherMap = {
    "name": name,
    "temp": temp,
    "description": description,
    "feels_like": feels_like,
    "temp_min": temp_min,
    "temp_max": temp_max,
    "pressure": pressure,
    "humidity": humidity,
    "wind_speed": wind_speed,
    "wind_dir": wind_dir,
    "clouds": clouds
}

JSON = json.dumps(OpenWeatherMap)
print(JSON)

import requests

api_key = '33cb808325c68f009bd043f19e5f591f'
city_name = "karachi"

current_weather_url = f"https://api.openweathermap.org/data/2.5/weather?q={city_name}&appid={api_key}"
response = requests.get(current_weather_url)
data = response.json()

lat = data['coord']['lat']
lon = data['coord']['lon']

forecast_url = f"https://api.openweathermap.org/data/2.5/onecall?lat={lat}&lon={lon}&exclude=current,minutely,hourly,alerts&appid={api_key}&units=metric"
forecast_response = requests.get(forecast_url)
forecast_data = forecast_response.json()

print(forecast_data)

# WeatherApi Api Fetch ----------------------------------------------------------------

api_key2 = 'c0b407bf72e34543a8765220241109'

city_name2 = "Karachi"
url2 = f"http://api.weatherapi.com/v1/current.json?key={api_key2}&q={city_name2}&aqi=no"
#print(url2)

req2 = requests.get(url2)
data2 = req2.json()
#print(data2)

name2 = data2['location']['name']
temp2 = data2['current']['temp_c']
description2 = data2['current']['condition']['text']
feels_like2 = data2['current']['feelslike_c']
temp_min2 = data2['current']['temp_c']
temp_max2 = data2['current']['temp_c']
pressure2 = data2['current']['pressure_mb']
humidity2 = data2['current']['humidity']
wind_speed2 = data2['current']['wind_mph']
wind_dir2 = data2['current']['wind_dir']
clouds2 = data2['current']['cloud']

print("Name:\t\t",name2)
print("Temerature:\t",temp2, "°C")
print("Description:\t",description2)
print("Feels Like:\t",feels_like2, "°C")
print("Temp Min:\t",temp_min2, "°C")
print("Temp Max:\t",temp_max2, "°C")
print("Pressure:\t",pressure2, "hPa")
print("Humidity:\t",humidity2, "%")
print("Wind Speed:\t",wind_speed2, "mph")
print("Wind Dir:\t",wind_dir2)
print("Clouds:\t\t",clouds2, "%")

WeatherApi = {
    "name": name2,
    "temp": temp2,
    "description": description2,
    "feels_like": feels_like2,
    "temp_min": temp_min2,
    "temp_max": temp_max2,
    "pressure": pressure2,
    "humidity": humidity2,
    "wind_speed": wind_speed2,
    "wind_dir": wind_dir2,
    "clouds": clouds2
}

JSON2 = json.dumps(WeatherApi)
print(JSON2)

# WeatherBit Api Fetch ------------------------------------------------------------------------

api_key4 = '57cac8d74936472e8650390b011cc6aa'

city_name4 = "Karachi"
url4 = f"http://api.weatherbit.io/v2.0/current?city={city_name4}&key={api_key4}"
#print(url4)

req4 = requests.get(url4)
data4 = req4.json()
#print(data4)

name4 = data4['data'][0]['city_name']
temp4 = data4['data'][0]['temp']
description4 = data4['data'][0]['weather']['description']
feels_like4 = data4['data'][0]['app_temp']
temp_min4 = data4['data'][0]['temp']
temp_max4 = data4['data'][0]['temp']
pressure4 = data4['data'][0]['pres']
humidity4 = data4['data'][0]['rh']
wind_speed4 = round(((data4['data'][0]['wind_spd']) * 2.23694) * 2)
wind_dir4 = data4['data'][0]['wind_dir']
clouds4 = data4['data'][0]['clouds']

print("Name:\t\t",name4)
print("Temerature:\t",temp4, "°C")
print("Description:\t",description4)
print("Feels Like:\t",feels_like4, "°C")
print("Temp Min:\t",temp_min4, "°C")
print("Temp Max:\t",temp_max4, "°C")
print("Pressure:\t",pressure4, "hPa")
print("Humidity:\t",humidity4, "%")
print("Wind Speed:\t",wind_speed4, "mph")
print("Wind Dir:\t",wind_dir4)
print("Clouds:\t\t",clouds4, "%")

WeatherBit = {
    "name": name4,
    "temp": temp4,
    "description": description4,
    "feels_like": feels_like4,
    "temp_min": temp_min4,
    "temp_max": temp_max4,
    "pressure": pressure4,
    "humidity": humidity4,
    "wind_speed": wind_speed4,
    "wind_dir": wind_dir4,
    "clouds": clouds4
}

JSON4 = json.dumps(WeatherBit)
print(JSON4)
