name: weather-forecast-ml

on:
  push:
    branches:
      - main  # or the branches you're pushing to

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      # Set up Python 3.10 environment (you can specify  more recent Python version if required)
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install required dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools==68.0.0 wheel==0.40.0
          python -m pip install --no-cache-dir -r requirements.txt

      # Optional: Install caching (to speed up subsequent builds)
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Running the ML model (replace 'model.py' with your actual script if needed)
      - name: Train model
        run: |
          python model.py

      # Running the Flask Backend File
      - name: Run Flask App
        run: |
          # Run Flask app in the background
          python app.py &
          sleep 10  # wait for Flask to start
          curl http://127.0.0.1:5000/predict
          curl http://127.0.0.1:5000/compare/Karachi
