name: weather-forecast-ml

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools==68.0.0 wheel==0.40.0
          python -m pip install --no-cache-dir -r requirements.txt

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Train model
        run: |
          python model.py

      - name: Install ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install ngrok

      - name: Start Flask app and ngrok tunnel
        run: |
          nohup python app.py > flask.log 2>&1 &
          sleep 10
          ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
          ngrok http 5000 > ngrok.log &
          sleep 10

      - name: Get public URL from ngrok
        id: get-ngrok-url
        run: |
          echo "Fetching ngrok public URL..."
          NGROK_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          echo "NGROK_URL=$NGROK_URL" >> $GITHUB_ENV
          echo "Public URL is: $NGROK_URL"

      - name: Test Flask API Endpoints
        run: |
          echo "Calling ${{ env.NGROK_URL }}/predict"
          curl -i ${{ env.NGROK_URL }}/predict
          echo "Calling ${{ env.NGROK_URL }}/compare/Karachi"
          curl -i ${{ env.NGROK_URL }}/compare/Karachi

      - name: Pull working ZAP Docker image
        run: |
          docker pull ghcr.io/zaproxy/zaproxy:stable

      - name: Run ZAP Baseline Scan (manual via Docker)
        run: |
          docker run --rm \
            -u $(id -u):$(id -g) \
            -v $(pwd):/zap/wrk/:rw \
            ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
            -t ${{ env.NGROK_URL }} \
            -J report_json.json \
            -w report_md.md \
            -r report_html.html


      - name: Upload ZAP HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report-html
          path: report_html.html

      - name: Upload ZAP Markdown Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report-md
          path: report_md.md

      - name: Upload ZAP JSON Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report-json
          path: report_json.json
